name: Watch Releases

on:
  schedule:
    - cron: "0 */1 * * *"  # Every 1 hours
  workflow_dispatch:
    inputs:
      force_notify:
        description: "Force notify even if release tag is same"
        required: false
        default: false
        type: boolean
      debug_session:
        description: 'Run tmate debug session'
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main

jobs:
  release-watcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Set FORCE_NOTIFY env
        run: |
          if [[ "${{ github.event.inputs.force_notify }}" == "true" ]]; then
            echo 'FORCE_NOTIFY=1' >> $GITHUB_ENV
          fi

      - name: Populate env file
        run: printenv | sed 's/=/="/; s/$/"/' > .env.empty

      - name: Setup tmate session
        if: github.event.inputs.debug_session == 'true'
        uses: mxschmitt/action-tmate@v3.22

      - name: Run Release Watcher
        if: github.event.inputs.debug_session != 'true'
        run: docker compose up --build --abort-on-container-exit
